# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: task_manager_backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - CORS_ORIGINS=http://localhost:3000,http://task_manager_frontend:3000
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: task_manager_frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://task_manager_backend:8000
    depends_on:
      - backend