name: task-manager

services:

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"

    volumes:
      - db_data:/data/db
      - db_data_config:/data/configdb

  backend:
    image: "omar8832/task-manager-backend:latest"
    build: ./backend
    container_name: task_manager_backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - CORS_ORIGINS=http://localhost:3000,http://task_manager_frontend:3000
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    image: "omar8832/task-manager-frontend:latest"
    build: ./frontend
    container_name: task_manager_frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://task_manager_backend:8000
    depends_on:
      - backend

volumes:
  db_data:
  db_data_config: